name: CI (Ubuntu)

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev qmake6 qt6-5compat-dev qt6-multimedia-dev qt6-svg-dev qt6-tools-dev-tools qt6-webengine-dev
    - name: Build
      env:
        DISTCFG: 1
      run: make -j4
    - uses: actions/upload-artifact@master
      with:
        name: qmc2-ubuntu-latest-${{ github.sha }}
        path: |
          qmc2-sdlmame
